tools:
  weather_info : False
  contact_person : False
  faq_tool : True
  show_map : False

model:
  llm: 
    version: "gpt-4o-mini"
    agent_thinking_visible : True
  embedding: 
    model_name: "text-embedding-3-small"
    chunk_size: 300
    chunk_overlap: 20

rag:
  datasets:
    - name: "kaga_fei_exhibition_faq"
      source_data: "data/kaga_fei_exhibition_faq.xlsx"
      vector_db: "data/kaga_fei_exhibition_faq_index"
      track_file: "data/timestamp_kaga_fei_exhibition.txt"

dailogue:
  rag_fallback_message: "ご質問いただきありがとうございます。大変申し訳ございませんが、勉強不足のためお答えいたしかねます。"
