tools:
  weather_info : False
  contact_person : False
  faq_tool : True
  websearch : False
  show_map : False

model:
  llm: 
    version: "gpt-4o-mini"
    agent_thinking_visible : True
  embedding: 
    model_name: "text-embedding-3-small"
    chunk_size: 300
    chunk_overlap: 20

rag:
  datasets:
    - name: "kaga_fei_exhibition_faq"
      source_data: "data/kaga_fei_exhibition_faq.xlsx"
      vector_db: "data/kaga_fei_exhibition_faq_index"
      track_file: "data/timestamp_kaga_fei_exhibition.txt"

dailogue:
  rag_fallback_message: "ご質問いただきありがとうございます。大変申し訳ございませんが、勉強不足のためお答えいたしかねます。力不足で恐縮ですが、どうかご理解いただけますと幸いです。"

greeting:
  greet_ja-JP : "こんにちは。ステラです。ご案内致しますので、何かお手伝いできることありますか？\n"
  greet_en-US : "Hello, I am Stella. How can I assist you today?\n"
  greet_zh-CN : "您好，我是Stella。我能为您做些什么？\n"
  greet_ko-KR : "안녕하세요. 스텔라입니다. 안내해 드리겠습니다. 무엇을 도와드릴까요?\n"
  greet_es-ES : "Hola, soy Stella. ¿En qué puedo ayudarte hoy?\n"
  end_ja-JP : "ご来場ありがとうございました。引き続き展示会をお楽しみください。\n"
  end_en-US : "Thank you for visiting. Please enjoy the rest of the exhibition!\n"
  end_zh-CN : "感谢您的到访。请继续享受接下来的展览！\n"
  end_ko-KR : "방문해 주셔서 감사합니다. 전시회를 계속 즐겨주세요!\n"
  end_es-ES : "¡Gracias por visitarnos! ¡Disfruta el resto de la exposición!\n"

display_text:
  ask_phone_text: "ご連絡先を\nお伺いいたします。"
  ask_wait_text : "お待ちいただけますでしょうか？"
  ask_name_phone_text : "お名前とご連絡先を\nお伺いいたします。"
  ask_need_callback_text: "折り返しのご連絡は\n必要ですか？"